language: csharp
solution: TravisExperiments.sln
 
 
script:
  - pwd
  - ls $NVM_DIR
  - ls $NVM_DIR/versions/node
  
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - mono ./TravisExperiments.exe 
