language: csharp
solution: TravisExperiments.sln
 
 
script:
  - nuget install FSharp.Compiler.Tools -Version 4.0.0.1 -OutputDirectory ./bin -ExcludeVersion
  - cp -r ./bin/FSharp.Compiler.Tools/tools ./bin
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - cd bin
  - mono ./TravisExperiments.exe
