language: csharp
solution: TravisExperiments.sln
 
 
script:
  - pwd
  - nvm which 0.10
  - nvm which 0.10.36
  
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - mono ./TravisExperiments.exe 
