language: csharp
solution: TravisExperiments.sln
 
 
script:
  - pwd
  - echo "$PWD"
  - cd
  - nuget install FSharp.Compiler.Tools -Version 4.0.0.1 -OutputDirectory ./bin -ExcludeVersion
  - export PATH=$PATH:./bin/FSharp.Compiler.Tools/tools/
  - mono fsc.exe
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - cd bin
  - mono ./TravisExperiments.exe
