language: csharp
solution: TravisExperiments.sln
 
 
script:
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - export MONO_REGISTRY_PATH=/tmp/test
  - find /tmp/test -name 'values.xml'
  - mono ./bin/TravisExperiments.exe