language: csharp
solution: TravisExperiments.sln
 
 
script:
  - pwd
  - export NODEJS=$(dirname `nvm which $NODEJS_VERSION`)
  - echo $NODEJS
  
  - xbuild /p:Configuration=Release /v:q TravisExperiments.sln
  - mono ./TravisExperiments.exe 
  
env:
  - $NODEJS_VERSION=0.10
